name: Flutter CI
on:
  push:
    branches: [ "main" ]
    paths:
      - "app/**"
      - ".github/workflows/flutter-ci.yml"
  pull_request:
    branches: [ "main" ]
    paths:
      - "app/**"
      - ".github/workflows/flutter-ci.yml"

jobs:
  analyze_and_test:
    if: ${{ hashFiles('app/pubspec.yaml') != '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter --version
      - working-directory: app
        run: flutter pub get
      - working-directory: app
        run: flutter analyze
      - working-directory: app
        run: flutter test --no-pub
