# 更新 flutter-ci.yml
cat > .github/workflows/flutter-ci.yml <<'YAML'
name: Flutter CI
on:
  push:
    branches: [ main ]
    paths:
      - "app/**"
  pull_request:
    branches: [ main ]
    paths:
      - "app/**"

jobs:
  analyze_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Flutter version
        run: flutter --version

      - name: Pub get
        working-directory: app
        run: flutter pub get

      - name: Analyze
        working-directory: app
        run: flutter analyze

      - name: Test
        working-directory: app
        run: flutter test --no-pub
YAML

git add .github/workflows/flutter-ci.yml
git commit -m "ci(flutter): trigger only on app/**; remove hashFiles"
git pull --rebase origin main
git push -u origin main
