name: Server CI
on:
  push:
    paths: ["server/**",".github/workflows/server-ci.yml"]
  pull_request:
    paths: ["server/**",".github/workflows/server-ci.yml"]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: server } }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: pytest -q
