name: Server CI
on:
  push:
    branches: [ "main" ]
    paths:
      - "server/**"
      - ".github/workflows/server-ci.yml"
  pull_request:
    branches: [ "main" ]
    paths:
      - "server/**"
      - ".github/workflows/server-ci.yml"

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    env:
      PYTHONPATH: ${{ github.workspace }}/server
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: pip
          cache-dependency-path: server/requirements.txt

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: pytest -q
